apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-movies
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-movies
  template:
    metadata:
      labels:
        app: go-movies
    spec:
      containers:
      - name: go-movies
        image: go-movie
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
